spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5430/news_service_db
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

cache:
  algorithm: LRU
  maxSize: 100